# Copyright (c) 2026 Tanmay Dikey <enceladus441@gmail.com>
# SPDX-License-Identifier: MIT
"""
AgentArmor — Shadow-Chain Manager
=====================================
Manages the persistent Attestation Shadow-Chain stored at:
    .agent-armor/shadow-chain.json

The Shadow-Chain is an append-only log of all code attestations
generated by AgentArmor.  It provides:

  1. Audit trail of every code block processed by AgentArmor
  2. Tamper detection — if a previously attested file is modified,
     verify() will return False, blocking CI/CD pipelines
  3. History — developers can see when a file's security posture changed

Chain format (JSON)
--------------------
    {
        "version": "1.0.0",
        "entries": [
            {
                "signature":  "a3f9b2...",
                "timestamp":  "2026-02-25T12:00:00Z",
                "filename":   "src/api.py",
                "invariants": {...},
                "prev_hash":  "chain_link_hash"
            },
            ...
        ],
        "chain_hash": "sha256 of all entries concatenated"
    }

The `prev_hash` field links each entry to its predecessor,
forming an immutable linked-chain (similar in concept to a blockchain).
This means you cannot silently delete a past attestation without
the chain_hash changing.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from ..core.attestation import Attestation

_CHAIN_VERSION = "1.0.0"
_DEFAULT_CHAIN_PATH = Path(".agent-armor") / "shadow-chain.json"


@dataclass
class ChainEntry:
    """A single entry in the Shadow-Chain."""
    signature: str
    timestamp: str
    filename: str
    invariants: dict
    prev_hash: str        # SHA-256 of the previous entry's signature + timestamp

    def to_dict(self) -> dict:
        return {
            "signature":  self.signature,
            "timestamp":  self.timestamp,
            "filename":   self.filename,
            "invariants": self.invariants,
            "prev_hash":  self.prev_hash,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "ChainEntry":
        return cls(
            signature=d["signature"],
            timestamp=d["timestamp"],
            filename=d.get("filename", "unknown"),
            invariants=d.get("invariants", {}),
            prev_hash=d.get("prev_hash", "GENESIS"),
        )

    @property
    def entry_hash(self) -> str:
        """SHA-256 of this entry's canonical representation."""
        payload = f"{self.signature}|{self.timestamp}|{self.filename}|{self.prev_hash}"
        return hashlib.sha256(payload.encode()).hexdigest()


class ShadowChainManager:
    """
    Manages the persistent Attestation Shadow-Chain.

    Usage::

        manager = ShadowChainManager()
        manager.record(attestation)
        history = manager.get_history(filename="src/api.py")
        is_valid = manager.verify_chain()
    """

    def __init__(
        self,
        chain_path: Optional[Path] = None,
        chain_dir: Optional[str] = None,
    ) -> None:
        if chain_dir is not None:
            # Convenience: accept a directory string; store chain inside it
            self._path = Path(chain_dir) / "shadow-chain.json"
        else:
            self._path = chain_path or _DEFAULT_CHAIN_PATH
        self._entries: List[ChainEntry] = []
        self._load()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record(self, attestation: Attestation) -> ChainEntry:
        """
        Append a new :class:`Attestation` to the chain and persist it.
        Returns the newly created :class:`ChainEntry`.
        """
        prev_hash = self._entries[-1].entry_hash if self._entries else "GENESIS"
        entry = ChainEntry(
            signature=attestation.signature,
            timestamp=attestation.timestamp,
            filename=attestation.filename,
            invariants=attestation.invariants,
            prev_hash=prev_hash,
        )
        self._entries.append(entry)
        self._save()
        return entry

    def verify_chain(self) -> bool:
        """
        Verify the integrity of the entire chain.
        Returns True if all prev_hash links are intact.
        """
        if not self._entries:
            return True

        # First entry must have GENESIS prev_hash
        if self._entries[0].prev_hash != "GENESIS":
            return False

        for i in range(1, len(self._entries)):
            expected = self._entries[i - 1].entry_hash
            if self._entries[i].prev_hash != expected:
                return False

        return True

    def verify_file_attestation(self, filename: str, current_sig: str) -> bool:
        """
        Check whether *current_sig* matches the most recent attestation
        for *filename* in the chain.
        """
        history = self.get_history(filename)
        if not history:
            return False
        latest = history[-1]
        return latest.signature == current_sig

    def get_history(self, filename: Optional[str] = None) -> List[ChainEntry]:
        """
        Return all chain entries, optionally filtered by *filename*.
        """
        if filename is None:
            return list(self._entries)
        return [e for e in self._entries if e.filename == filename]

    def get_latest(self, filename: str) -> Optional[ChainEntry]:
        """Return the most recent chain entry for *filename*."""
        history = self.get_history(filename)
        return history[-1] if history else None

    def summary(self) -> dict:
        """Return a summary of the chain."""
        return {
            "version": _CHAIN_VERSION,
            "total_entries": len(self._entries),
            "chain_valid": self.verify_chain(),
            "files_attested": len({e.filename for e in self._entries}),
            "latest_timestamp": self._entries[-1].timestamp if self._entries else None,
        }

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _load(self) -> None:
        """Load the chain from disk."""
        try:
            if self._path.exists():
                data = json.loads(self._path.read_text(encoding="utf-8"))
                self._entries = [ChainEntry.from_dict(e) for e in data.get("entries", [])]
        except Exception:
            self._entries = []

    def _save(self) -> None:
        """Persist the chain to disk."""
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            chain_hash = hashlib.sha256(
                "|".join(e.entry_hash for e in self._entries).encode()
            ).hexdigest()
            data = {
                "version": _CHAIN_VERSION,
                "chain_hash": chain_hash,
                "entries": [e.to_dict() for e in self._entries],
            }
            self._path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except Exception:
            pass
